name: baymind
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # Asegúrate de usar una versión compatible (esto es solo un ejemplo)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
